### ISSUE TITLE
getpeerinfo return only 0.000

### ISSUE THREAD

**Issue by limxdev** [LIMXTEC/BitSend#13]
I add for the QT Wallet a peerinfo tab. But getpeerinfo return only 0.000

Bounty 2000 BSD

net.cpp
https://github.com/LIMXTEC/BitSend/blob/master/src/net.cpp#L618

getpeerinfo
  {
        "addr" : "37.120.190.76",
        "services" : "00000001",
        "lastsend" : 1489230175,
        "lastrecv" : 1489230179,
        "bytessent" : 277,
        "bytesrecv" : 34276,
        "conntime" : 1489230171,
        "pingtime" : 0.00000000,
}

**Comment by bitbandi** [comment]
this is "normal", pings are send if it is requested by rpc or by keep alive:
https://github.com/LIMXTEC/BitSend/blob/master/src/main.cpp#L4963-L4971

If you are downloading blockchain, etc., no ping. If you want to see pingtime, request a "ping all node" in rpc (by "ping" command).

**Comment by limxdev** [comment]
I am not sure... here is the problem. (This is a new version with peertab)

https://dl.dropboxusercontent.com/u/21000833/Bitsend/DEV/WhatsApp%20Image%202017-03-12%20at%2000.36.54.jpeg

It returns always zero....  
https://github.com/LIMXTEC/BitSend/blob/Test/src/qt/guiutil.cpp#L801:L805

**Comment by bitbandi** [comment]
did you made a "ping" rpc call before the screenshot?

**Comment by joshafest** [comment]
If node is already connected, then ping time =0 is normal

**Comment by limxdev** [comment]
"did you made a "ping" rpc call before the screenshot?"
I try with geetpeer before after etc... it is always 0.

If node is already connected, then ping time =0 is normal
By ERC,B3,LTC,BTC, DAHS works it correct

You it test on the new windows version. (It is a other peer tab) 
https://github.com/LIMXTEC/BitSend/releases

**Comment by bitbandi** [comment]
Apply this commit: https://github.com/dashpay/dash/commit/f1920e86063d0ed008c6028d8223b0e21889bf75 :

    wget https://github.com/dashpay/dash/commit/f1920e86063d0ed008c6028d8223b0e21889bf75.patch
    patch -i f1920e86063d0ed008c6028d8223b0e21889bf75.patch -p1

**Comment by limxdev** [comment]
Okay I try it later

**Comment by limxdev** [comment]
Thank you ... Bounty payed 
7f67184ca61fbf05754e3e8d30d2ee5e882ee09bca2e29bd05ba44659716e084-000
