### ISSUE TITLE
debug blow by masternodes

### ISSUE THREAD

**Issue by limxdev** [LIMXTEC/BitSend#15]
The debug file will shrink by every wallet start. But not if the masternode is 24/7 running. We need here a daily cronejob or a max file size function.

https://dl.dropboxusercontent.com/u/21000833/Bitsend/DEV/Debug.JPG

Bounty 2000 BSD

**Comment by bitbandi** [comment]
Use `if(fDebug)` conditions before LogPrintf calls:
https://github.com/LIMXTEC/BitSend/blob/master/src/main.cpp#L2822-L2907

like here: https://github.com/LIMXTEC/BitSend/blob/master/src/main.cpp#L2838

**Comment by limxdev** [comment]
Thank you, I know what you mean. I search a solution to cut the max size ...But that is also possible.

**Comment by limxdev** [comment]
We test now a possible solution...

https://github.com/LIMXTEC/BitSend/commit/650fc88590c21df527de857263e0bcfbb8640bf1

**Comment by limxdev** [comment]
Is fixed
