### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by limxdev** [LIMXTEC/BitSend#18]
Some Wallets can't connect without addnode...seednodes are all online. 

https://github.com/LIMXTEC/BitSend/blob/master/src/chainparams.cpp

2017-03-16 18:21:12 socket recv error  (10053)
2017-03-16 18:21:22 socket recv error  (10053)
2017-03-16 18:21:34 socket recv error  (10053)
2017-03-16 18:21:47 socket recv error  (10053)
2017-03-16 18:22:46 socket recv error (10053)
2017-03-16 18:23:01 socket recv error  (10053)

**Comment by ghost** [comment]
These may help for those that are looking into this:
https://stackoverflow.com/questions/17623563/c-winsock-error-10053 
https://stackoverflow.com/questions/15433380/socket-programming-update-recv-returning-1-error-10053
https://wiki.pscs.co.uk/how_to:10053

Could you post the steps to reproduce?

**Comment by limxdev** [comment]
https://github.com/LIMXTEC/BitSend/blob/master/src/net.cpp#L1005

Hmm... seems fine. 

"Could you post the steps to reproduce?" 
No, one or two users told me that.

**Comment by ghost** [comment]
Strange. We can't do much about it if we are unable to reproduce it. They may have been on some older version?

**Comment by limxdev** [comment]
It is also possible...
