### ISSUE TITLE
Set a valid pubkey to burned address. 

### ISSUE THREAD

**Issue by limxdev** [LIMXTEC/BitSend#24]
We want to burn 1 MIO BSD (Old Premine Coins) 

The address is iAm2Ag9hf5waYS3QZSfJSS5ibRQ2Z4NfB7. We need here a DOS100 function to lock the Coins. 

The Bounty for a good solution is 2000 BSD.

**Comment by Elbandi** [comment]
create a raw transaction to this address: i3UXS5QPRQGNRDDqVnyWTnmFCTHDbzmsYk

and decode the raw transaction, you will see the output script key:

    OP_DUP OP_HASH160 0000000000000000000000000000000000000000 OP_EQUALVERIFY OP_CHECKSIG

this is unspendable

**Comment by bitbandi** [comment]
create a raw transaction to this address: i3UXS5QPRQGNRDDqVnyWTnmFCTHDbzmsYk

and decode the raw transaction, you will see the output script key:

    OP_DUP OP_HASH160 0000000000000000000000000000000000000000 OP_EQUALVERIFY OP_CHECKSIG

this key un unspendable

**Comment by limxdev** [comment]
Thank you bitbandi. It is not possible to move the coins.

**Comment by Elbandi** [comment]
why is not possible to move?

**Comment by bitbandi** [comment]
why is not possible to move?

**Comment by limxdev** [comment]
A imposter has received coins from the Dev Found.  The coins are locked on bittrex. 

https://dl.dropboxusercontent.com/u/21000833/Bitsend/WhatsApp%20Image%202017-03-22%20at%2022.14.13.jpeg

**Comment by bitbandi** [comment]
well. if the coin is in exchange, and you "lock" the coin in blockchain, you sould still trust the exchange. thats not a real burn....

anyway. if the coins are in bittrex address, they have the privkey so they can send to a burn address.

**Comment by limxdev** [comment]
Yes that is best solution but we talk now since 273 days about a solution.

**Comment by joshafest** [comment]
The address is not typically public key. It is hash of public key ... So, if we know only hash of public key, it is not feasible to get public key. Moreover if even we got public key, we can't get it's private key.. 
So, burning seems to be impossible if this is ...

**Comment by limxdev** [comment]
It is possible to write a function like this here. https://github.com/LIMXTEC/BitSend/blob/master/src/main.cpp#L2890

Example:
if((blockheight > 198403)&& (lasttx move pubkey) Dos100 ... 
This block is then a orphan. 

 It is only a backup.

**Comment by limxdev** [comment]
Is still open...

**Comment by joshafest** [comment]
? ?  You closed it ?

**Comment by bitbandi** [comment]
or you can set there a check to prevent the sending, so you lock the coins to that output:
https://github.com/LIMXTEC/BitSend/blob/master/src/main.cpp#L814

    if (txin.prevout == COutPoint(uint256("0x3d1c1cfd63e59a8c207d9a1d65e1446973da88120659d8e50032f3ee7c893550"), 0))
        return state.DoS(100, error("CheckTransaction() : imposter locked tx", REJECT_INVALID, "bad-cb-lock");

**Comment by joshafest** [comment]
@bitbandi Are whole coins packed in single transaction ?

**Comment by joshafest** [comment]
I think yes, whole bunch is of single received transaction. 
Will lock this in next update I.e. version 0.14

**Comment by bitbandi** [comment]
@joshafest the address has one input: https://chainz.cryptoid.info/bsd/address.dws?iAm2Ag9hf5waYS3QZSfJSS5ibRQ2Z4NfB7.htm

**Comment by limxdev** [comment]
Did you have tested it @bitbandi ? I can it only note as backup. This solution is for Bittrex imposible.

**Comment by bitbandi** [comment]
no tested, but....

What is the good solution for bittrex and for _bitsend communinty_? bittrex promise scout's honor, that they wont touch the coins? well, thats not a burned coint...

they have the privkey for that address, the sould withdraw the coin to the burn address. or you can "lock" the transaction to unspendable. no other solutions are possible...

**Comment by joshafest** [comment]
@bitbandi , @limxdev blockchain works on consensus, if the community announced the transaction as invalid and 60% of users/community agrees it. It will became invalid and bittrex cannot move her coins .
Bitbandi's solution is good.

**Comment by limxdev** [comment]
bitbandi I want to a small bounty. Please give me your address.

**Comment by joshafest** [comment]
@chris , bitbandi's solution is 'NOT' burning coins ... It is 'FREEZING' the coins, so that they cannot be claimed.

**Comment by bitbandi** [comment]
@joshafest well, the _true_ unspendable output need a special transaction:
https://en.bitcoin.it/wiki/Script#Provably_Unspendable.2FPrunable_Outputs

And sending to a 0 pubkeyhash address is "almost good" solutions (you need to find a privkey for 0 pubkeyhash, 2^256 check, good luck! :D ) . But none of them are acceptable by bittrex.

With that "no-send" criterion, the transaction lock is a good solution.

**Comment by joshafest** [comment]
Yes, as I say your solution is good. .. :)
