### ISSUE TITLE
"error: 'DIFF_KGW3' was not declared in this scope" compilation issue

### ISSUE THREAD

**Issue by Kasvain** [LIMXTEC/BitSend#3]
Hi!
I'm trying to compile a wallet daemon on a Debian 9 machine, I have GCC 5.3.1, BDB 5.3, GLIBCXX v. 3.4.21 and Boost 1.58.

I configured the build with parameters `--with-incompatible-bdb --without-gui`
Earlier LIMX wallet versions and other Core 0.12+ wallets compiles without errors with those parameters, but BSD wallet compilation outputs following:

```
  CXX      main.o
main.cpp: In function 'unsigned int GetNextWorkRequired(const CBlockIndex*, const CBlockHeader*)':
main.cpp:1557:62: error: 'DIFF_KGW3' was not declared in this scope
          if (pindexLast->nHeight + 1 >= 139975) { retarget = DIFF_KGW3; if (pindexLast->nHeight < 141000) LogPrintf("KGW3"); }
                                                              ^
main.cpp:1648:30: error: 'DIFF_KGW3' was not declared in this scope
         else if (retarget == DIFF_KGW3)
                              ^
main.cpp:1678:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:926: recipe for target 'main.o' failed
make[3]: *** [main.o] Error 1
```

Appreciate if a solution is found,
Thanks in advance

**Comment by limxdev** [comment]
Hello,

thank you for your report. I've it fixed.

Best Regards Christian

**Comment by Kasvain** [comment]
Thanks, such quick response. :+1:  I'll try to recompile soon!
