### ISSUE TITLE
build failure on <ubu16/stretch/mint18/fedora24

### ISSUE THREAD

**Issue by JazzMaster** [LIMXTEC/BitSend#35]
I cant speak for fedora specifically but I know recent changes and updates, I believe after 23 hardened linux. Normally not an issue unless we are on a miner, which is OUT OF DATE.

mint 18 removes catalyst for crimson amdgpu driver, so Ill have to assume they are following.

Your GUI build fails. 
You need the following option. No changes to Makefile are examined(maybe they should be).

Install backports. Install qt5 (w instruction from MuseScore for deps) and then issue this:

env CFLAGS="-fPIC" make
to force PIC mode (which qt5 needs?).

Your welcome, miners. Took me forever to figure out.

**Comment by limxdev** [comment]
Hello,

do you write about the GPU Miner or our QT- Wallet?
https://github.com/LIMXTEC/Xevan-GPU-Miner

Kind Regards Christian
