### ISSUE TITLE
Show a little symbol  in the right corner if masternode is online.

### ISSUE THREAD

**Issue by limxdev** [LIMXTEC/BitSend#37]
Show a little symbol  in the right corner if masternode is online.

- Only for QT Version
- symbol = (picture in right corner)
- only possible for hot masternodes
https://dl.dropboxusercontent.com/u/21000833/Bitsend/DEV/Issusright%20corner.JPG

rpc command is masternode debug 

Bounty is 1000 BSD

**Comment by ghost** [comment]
Any ideas for the icons? We'd need two (one for disabled by default and one for enabled).

**Comment by bitbandi** [comment]
Error (429) :/

**Comment by joshafest** [comment]
@bitbandi ?? compilation ?

**Comment by joshafest** [comment]
This is small work , I think easy to do.

**Comment by joshafest** [comment]
https://github.com/LIMXTEC/BitSend/commit/34c0e5958a698078e5f90f6094df2e462cb6227c

fixed
