### ISSUE TITLE
Build error Ubuntu 16.04.2 LTS

### ISSUE THREAD

**Issue by gkucmierz** [LIMXTEC/BitSend#38]
<img width="667" alt="zrzut ekranu 2017-04-14 o 00 33 41" src="https://cloud.githubusercontent.com/assets/739084/25027204/362459b0-20ab-11e7-998a-c28fa0ad98b9.png">

**Comment by ghost** [comment]
I'll test this out myself as soon as I can. Ubuntu 16.04 is not officially supported (14.04 should work flawlessly). You may want to hide your IP in that image.

**Comment by limxdev** [comment]
Is fixed
