### ISSUE TITLE
Bounty for a fast coin controll function.

### ISSUE THREAD

**Issue by limxdev** [LIMXTEC/BitSend#5]
But...a little problem has our wallet. The function coin control is too slow. Bitcoin has the same problem!

You can test it with a testwallet. XCHWrkajRBNBc84xgCnTsnxWzVCvW32GvvtGUNpz9xJr3AtcAR9M  (debug -> importprivkey (please create a new wallet for this key))
The wallet has 111 pubkeys with over 700 TX per pubkey. You can send coin only with coin control. Here must you select the pubkeys by hand.
This is process running very slow. I think we need here a multicore support. The function use only one thread.

I 'll pay a bounty for a fast coin controll function in the QT Wallet. ( 150 BSD per week)
https://github.com/LIMXTEC/BitSend/blob/master/src/qt/coincontroldialog.cpp#L1

I think the function is very important for the future.

Best Regards Christian

**Comment by joshafest** [comment]
well .....i am unable to understand it (my bad english)

you mean import the key and then try to send coins with coin control?...or?

**Comment by limxdev** [comment]
Yes, we need more performance for this function. It's to slow by  heavy wallets with to much transactions.

**Comment by joshafest** [comment]
we need to add additional info in wallet.dat 
so that import only search that blocks that are usefull ... 
not the whole blockchain.

**Comment by limxdev** [comment]
It works fine...
