### ISSUE TITLE
build failing Ubuntu 16.04

### ISSUE THREAD

**Issue by crombiecrunch** [LIMXTEC/BitSend#58]
trying to build this on 16.04 and getting the following error:

> In file included from qt/test/rpcnestedtests.cpp:12:0:
./rpcconsole.h:61:9: error: expected ‘:’ before ‘slots’
 private slots:
         ^
./rpcconsole.h:61:9: error: ‘slots’ does not name a type
./rpcconsole.h:74:8: error: expected ‘:’ before ‘slots’
 public slots:
        ^
./rpcconsole.h:74:8: error: ‘slots’ does not name a type
./rpcconsole.h:91:1: error: ‘signals’ does not name a type
 signals:
 ^
qt/test/rpcnestedtests.cpp: In member function ‘void RPCNestedTests::rpcNestedTests()’:
qt/test/rpcnestedtests.cpp:65:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "getblockchaininfo()[c
     ^
qt/test/rpcnestedtests.cpp:69:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "getblock(getbestblock
     ^
qt/test/rpcnestedtests.cpp:70:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "getblock(getblock(get
     ^
qt/test/rpcnestedtests.cpp:72:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "getblock( getblock( g
     ^
qt/test/rpcnestedtests.cpp:74:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "getblockchaininfo");
     ^
qt/test/rpcnestedtests.cpp:77:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "getblockchaininfo()")
     ^
qt/test/rpcnestedtests.cpp:80:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "getblockchaininfo ");
     ^
qt/test/rpcnestedtests.cpp:83:6: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     (RPCConsole::RPCExecuteCommandLine(result, "getblockchaininfo()[
      ^
qt/test/rpcnestedtests.cpp:86:6: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     (RPCConsole::RPCExecuteCommandLine(result, "createrawtransaction
      ^
qt/test/rpcnestedtests.cpp:87:6: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     (RPCConsole::RPCExecuteCommandLine(result2, "createrawtransactio
      ^
qt/test/rpcnestedtests.cpp:89:6: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     (RPCConsole::RPCExecuteCommandLine(result2, "createrawtransactio
      ^
qt/test/rpcnestedtests.cpp:92:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "getblock(getbestblock
     ^
qt/test/rpcnestedtests.cpp:96:5: error: ‘RPCParseCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCParseCommandLine(result, "importprivkey", false,
     ^
qt/test/rpcnestedtests.cpp:98:5: error: ‘RPCParseCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCParseCommandLine(result, "signmessagewithprivkey
     ^
qt/test/rpcnestedtests.cpp:100:5: error: ‘RPCParseCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCParseCommandLine(result, "signmessagewithprivkey
     ^
qt/test/rpcnestedtests.cpp:102:5: error: ‘RPCParseCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCParseCommandLine(result, "signrawtransaction(abc)
     ^
qt/test/rpcnestedtests.cpp:104:5: error: ‘RPCParseCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCParseCommandLine(result, "walletpassphrase(help()
     ^
qt/test/rpcnestedtests.cpp:106:5: error: ‘RPCParseCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCParseCommandLine(result, "walletpassphrasechange(
     ^
qt/test/rpcnestedtests.cpp:108:5: error: ‘RPCParseCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCParseCommandLine(result, "help(encryptwallet(abc,
     ^
qt/test/rpcnestedtests.cpp:110:5: error: ‘RPCParseCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCParseCommandLine(result, "help(importprivkey())",
     ^
qt/test/rpcnestedtests.cpp:112:5: error: ‘RPCParseCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCParseCommandLine(result, "help(importprivkey(help
     ^
qt/test/rpcnestedtests.cpp:114:5: error: ‘RPCParseCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCParseCommandLine(result, "help(importprivkey(abc)
     ^
qt/test/rpcnestedtests.cpp:117:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "rpcNestedTest");
     ^
qt/test/rpcnestedtests.cpp:119:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "rpcNestedTest ''");
     ^
qt/test/rpcnestedtests.cpp:121:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "rpcNestedTest \"\"");
     ^
qt/test/rpcnestedtests.cpp:123:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "rpcNestedTest '' abc"
     ^
qt/test/rpcnestedtests.cpp:125:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "rpcNestedTest abc ''
     ^
qt/test/rpcnestedtests.cpp:127:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "rpcNestedTest abc  ab
     ^
qt/test/rpcnestedtests.cpp:129:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "rpcNestedTest abc\t\t
     ^
qt/test/rpcnestedtests.cpp:131:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "rpcNestedTest(abc )")
     ^
qt/test/rpcnestedtests.cpp:133:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "rpcNestedTest( abc )"
     ^
qt/test/rpcnestedtests.cpp:135:5: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     RPCConsole::RPCExecuteCommandLine(result, "rpcNestedTest(   abc
     ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtTest/qtest.h:38:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtTest/QTest:1,
                 from qt/test/rpcnestedtests.h:9,
                 from qt/test/rpcnestedtests.cpp:5:
qt/test/rpcnestedtests.cpp:140:30: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     QVERIFY_EXCEPTION_THROWN(RPCConsole::RPCExecuteCommandLine(resul
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtTest/qtestcase.h:93:17: note: in definition of macro ‘QVERIFY_EXCEPTION_THROWN’
                 expression;\
                 ^
qt/test/rpcnestedtests.cpp:141:30: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     QVERIFY_EXCEPTION_THROWN(RPCConsole::RPCExecuteCommandLine(resul
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtTest/qtestcase.h:93:17: note: in definition of macro ‘QVERIFY_EXCEPTION_THROWN’
                 expression;\
                 ^
qt/test/rpcnestedtests.cpp:142:6: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     (RPCConsole::RPCExecuteCommandLine(result, "getblockchaininfo(")
      ^
qt/test/rpcnestedtests.cpp:143:6: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     (RPCConsole::RPCExecuteCommandLine(result, "getblockchaininfo()(
      ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtTest/qtest.h:38:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtTest/QTest:1,
                 from qt/test/rpcnestedtests.h:9,
                 from qt/test/rpcnestedtests.cpp:5:
qt/test/rpcnestedtests.cpp:144:30: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     QVERIFY_EXCEPTION_THROWN(RPCConsole::RPCExecuteCommandLine(resul
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtTest/qtestcase.h:93:17: note: in definition of macro ‘QVERIFY_EXCEPTION_THROWN’
                 expression;\
                 ^
qt/test/rpcnestedtests.cpp:145:30: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     QVERIFY_EXCEPTION_THROWN(RPCConsole::RPCExecuteCommandLine(resul
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtTest/qtestcase.h:93:17: note: in definition of macro ‘QVERIFY_EXCEPTION_THROWN’
                 expression;\
                 ^
qt/test/rpcnestedtests.cpp:146:30: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     QVERIFY_EXCEPTION_THROWN(RPCConsole::RPCExecuteCommandLine(resul
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtTest/qtestcase.h:93:17: note: in definition of macro ‘QVERIFY_EXCEPTION_THROWN’
                 expression;\
                 ^
qt/test/rpcnestedtests.cpp:147:30: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     QVERIFY_EXCEPTION_THROWN(RPCConsole::RPCExecuteCommandLine(resul
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtTest/qtestcase.h:93:17: note: in definition of macro ‘QVERIFY_EXCEPTION_THROWN’
                 expression;\
                 ^
qt/test/rpcnestedtests.cpp:148:30: error: ‘RPCExecuteCommandLine’ is not a member of ‘RPCConsole’
     QVERIFY_EXCEPTION_THROWN(RPCConsole::RPCExecuteCommandLine(resul
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtTest/qtestcase.h:93:17: note: in definition of macro ‘QVERIFY_EXCEPTION_THROWN’
                 expression;\
                 ^
Makefile:8690: recipe for target 'qt/test/qt_test_test_bitsend_qt-rpcnestedtests.o' failed
make[2]: *** [qt/test/qt_test_test_bitsend_qt-rpcnestedtests.o] Error 1
make[2]: Leaving directory '/home/ubuntu/BitSend/src'
Makefile:9738: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/BitSend/src'
Makefile:687: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

>

**Comment by joshafest** [comment]
@crombiecrunch 
disable gui tests

**Comment by joshafest** [comment]
these files get included from old version , you need to skip tests , we will fix this issue in next 2-3 hours

**Comment by joshafest** [comment]
pass this in `./configure`, `--disable-gui-tests`

**Comment by joshafest** [comment]
https://github.com/LIMXTEC/BitSend/commit/31b9fdc667008cf67c8a1679a331aa4ce4e004d5

this fixed

**Comment by joshafest** [comment]
@crombiecrunch try it now

**Comment by crombiecrunch** [comment]
thank you

**Comment by joshafest** [comment]
@crombiecrunch , is issue fixed? if yes , please close it.
