### ISSUE TITLE
New build fail Ubuntu 16.04

### ISSUE THREAD

**Issue by crombiecrunch** [LIMXTEC/BitSend#59]
`net_processing.cpp: In function ‘void ProcessGetData(CNode*, const Consensus::Params&, CConnman&, const std::atomic<bool>&)’:
net_processing.cpp:1161:86: error: ‘MSG_TXLOCK_REQUEST’ was not declared in this scope
             else if (inv.type == MSG_TX || inv.type == MSG_WITNESS_TX || inv.type == MSG_TXLOCK_REQUEST || inv.type == MSG_MASTERNODE_SCANNING_ERROR || inv.type == MSG_MASTERNODE_WINNER || inv.typ
                                                                                      ^
net_processing.cpp:1161:227: error: ‘MSG_TXLOCK_VOTE’ was not declared in this scope
 | inv.type == MSG_WITNESS_TX || inv.type == MSG_TXLOCK_REQUEST || inv.type == MSG_MASTERNODE_SCANNING_ERROR || inv.type == MSG_MASTERNODE_WINNER || inv.type == MSG_SPORK || inv.type == MSG_TXLOCK_
                                                                                                                                                                                          ^
Makefile:6212: recipe for target 'libbitsend_server_a-net_processing.o' failed
make[2]: *** [libbitsend_server_a-net_processing.o] Error 1
make[2]: Leaving directory '/home/ubuntu/BitSend/src'
Makefile:9738: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/BitSend/src'
Makefile:687: recipe for target 'all-recursive' failed
`

**Comment by joshafest** [comment]
ok I think it is due to new commits, let me fix it

**Comment by joshafest** [comment]
@crombiecrunch , please test it and close issue if it working

**Comment by crombiecrunch** [comment]
working

**Comment by limxdev** [comment]
Good work
