### ISSUE TITLE
Version 0.14.0.2

### ISSUE THREAD

**Issue by limxdev** [LIMXTEC/BitSend#61]
The wallet can't read the masternode.conf file.

**Comment by joshafest** [comment]
432a4069e36dcb497fc78babcca86a146ff4bbcb

This fixed the issue

**Comment by ghost** [comment]
0.14.0.3 still doesn't read masternode.conf

**Comment by joshafest** [comment]
it read , what's you trying?

**Comment by ghost** [comment]
@joshafest 
That I have:
1. Bitsend-qt
2. correctly filled masternode.conf (mn1 privkey trans-id)

When I start Bitsend-qt and I open the section Masternode, I don't see the masternode there. But if I from the menu select item to edit masternode.conf that the file opens.

**Comment by joshafest** [comment]
click start-all
