### ISSUE TITLE
[Doc] Masternode build Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [LIMXTEC/BitSend#66]
This document should be updated for the new LTS version of Ubuntu, 16.04. In its current state, it does not work and has a problem with the following:
`sudo apt-get install libboost1.54-all-dev`

The version that can be installed in 16.04 with a command is 1.58. It does not work when using the binaries available here:
https://github.com/LIMXTEC/BitSend/releases/tag/BSD1271

**Comment by ghost** [comment]
In Ubuntu 16.04 already collected files don't work, they aren't started. From Linux.tar.gz archive

**Comment by joshafest** [comment]
What is the problem?, I didn't get it

**Comment by ghost** [comment]
@joshafest 
![2017-10-01 15-22-13](https://user-images.githubusercontent.com/18265958/31054497-6c8c69b0-a6bc-11e7-9f90-a7353a287577.png)

**Comment by ghost** [comment]
I after all managed to execute start of this application. But I consider that it isn't normal when the ordinary user has to dance with a tambourine.

1. problem libdb 4.8
decision here
https://github.com/bitcoin/bitcoin/issues/3686

2. problem libevent_pthreads-2.0.so.5
decision here
https://ubuntuforums.org/showthread.php?t=2201974

**Comment by ghost** [comment]
probably it is possible to use new libdb5.3 (which is in repositories) instead of libddb4.8. For example Dash purse doesn't demand at all what dependences
