### ISSUE TITLE
QT- Issues -Masternode Tab shows not Missing Masternodes

### ISSUE THREAD

**Issue by limxdev** [LIMXTEC/BitSend#69]
The masternode tab "My Masternodes" shows only the working masternodes. It is but possible to start the missing masternodes with the button.

![grafik](https://user-images.githubusercontent.com/10200540/31197958-13194094-a953-11e7-98a4-9292d0a1446d.png)

This issues is important. The user can't see not working Masternodes.

**Comment by ghost** [comment]
https://github.com/LIMXTEC/BitSend/issues/61
I wrote already here about this problem

**Comment by joshafest** [comment]
@ElvisPresly,  then please close that issue , I think it is fixed by kaali ..

**Comment by ghost** [comment]
@joshafest I cannot close. I am not a topic starter
