### ISSUE TITLE
is this a normal error - I ask because my wallet keep stopping

### ISSUE THREAD

**Issue by jjj092353** [LIMXTEC/BitSend#7]
Updating '/home/coins/BitSend/src/qt/locale/bitsend_zh_HK.qm'...
    Generated 1001 translation(s) (1001 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)
/bin/sed -e '/^**._Created:/d' qrc_bitsend.cpp > qrc_bitsend.cpp.n && mv qrc_bitsend.cpp{.n,}
/bin/sed -e '/^\_*._by:/d' qrc_bitsend.cpp  > qrc_bitsend.cpp.n && mv qrc_bitsend.cpp{.n,}
make  all-recursive
make[4]: Entering directory `/home/coins/BitSend/src/qt'
Making all in .
make[5]: Entering directory`/home/coins/BitSend/src/qt'
  CXX      libbitsendqt_a-bitsend.o
In file included from /usr/include/qt5/QtGui/qwindowdefs.h:45:0,
                 from /usr/include/qt5/QtWidgets/qwidget.h:45,
                 from /usr/include/qt5/QtWidgets/qmainwindow.h:45,
                 from /usr/include/qt5/QtWidgets/QMainWindow:1,
                 from bitcoingui.h:12,
                 from bitsend.cpp:10:
/usr/include/qt5/QtCore/qglobal.h:1008:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC or -fPIE."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^
make[5]: *_\* [libbitsendqt_a-bitsend.o] Error 1
make[5]: Leaving directory `/home/coins/BitSend/src/qt'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory`/home/coins/BitSend/src/qt'
make[3]: **\* [all] Error 2
make[3]: Leaving directory `/home/coins/BitSend/src/qt'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory`/home/coins/BitSend/src'
make[1]: **\* [all] Error 2
make[1]: Leaving directory `/home/coins/BitSend/src'
make: **\* [all-recursive] Error 1
root@vps81309:/home/coins/BitSend#

**Comment by limxdev** [comment]
Hello, 

no that is not normal. Try it with   "Compile your code with -fPIC or -fPIE." 

Best Regards Christian

**Comment by jjj092353** [comment]
when you say compile -do I need to change the 'make' file that you supply? - I'm not sure where to supply this compile option

**Comment by joshafest** [comment]
there is a lot problem in compiling with normal windows mingw compiler especially in test.
a lot code need to repaired to get compiled well in normal pc. But no  issues with autogen; a lot with qt

**Comment by jjj092353** [comment]
i'm compiling without qt in linux for a pool

**Comment by joshafest** [comment]
In upcoming (next ) version this issue will get fixed. 
For now you can you autogen.sh ...it should work well ...ignore warning s

**Comment by joshafest** [comment]
please close this issue.
