### ISSUE TITLE
Core - Initialdownload 

### ISSUE THREAD

**Issue by limxdev** [LIMXTEC/BitSend#71]
Unknow error 

![grafik](https://user-images.githubusercontent.com/10200540/31199400-834cb838-a957-11e7-9651-2336ce9aa78e.png)

We need a solution for reference node tos. If masternodepaymentskey = true then need we a a disable from Spork check. Spork should only works if we send a new spork command.

**Comment by joshafest** [comment]
This issue arises due to isInitialBlockChainDownload,
it get relaxed after only header download

**Comment by joshafest** [comment]
This issue killing me, @Kaali Singh please fix this issue ASAP.

**Comment by Kaali** [comment]
Wrong person =)

**Comment by joshafest** [comment]
commit `1b76cae397456600fcf05beeba8c143dc1bc86a3`
close it after test
