### ISSUE TITLE
bitsendd: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by djspacedevil** [LIMXTEC/BitSend#74]
Hy, 

when i will start the new version i become the error:
``
bitsendd: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory
``
Ubuntu 
Linux *.de 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Comment by joshafest** [comment]
please pass your boost flags when you run ./configure 
like 
./configure BOOST_ROOT= <PATH>

**Comment by djspacedevil** [comment]
hy, i use the precompiled version. so i dont use the configure

i replace newer libdb5* with 4.8 and now it works.
apt-get install libdb4.8-dev
apt-get install libdb4.8++-dev

an make the normal ./configure and it runs ;) 

But i must reload the blockchain... i become the error 
``
ERROR: AcceptBlockHeader: block 0000000001065bff7654dcec3f8344d8832d2d5d39ce137937c488bc9fd186d7 is marked invalid
``
and this kill bitsendd

**Comment by joshafest** [comment]
please delete the chain and resync.
Please try to repeat the process, I want to know that issue in deep.

**Comment by rainmanp7** [comment]
I'm running Linux mint 64 bit. 
Tried to compile same issues.
I have removed the 5.* And replaced with the 4.8
Same..
If you say delete the block chain and resync?
Instruct how please.

Just trying to compile.

**Comment by djspacedevil** [comment]
the problem is still alive... on every block found, the wallet crash and the block is rejected... 
i recompiled, but this dont help...

**Comment by Kwaskoff** [comment]
http://archive.ubuntu.com/ubuntu/pool/main/b/boost1.58/
/./usr/lib/x86_64-linux-gnu/  ->> /usr/lib/
profit

**Comment by lydhr** [comment]
````
wget http://archive.ubuntu.com/ubuntu/pool/main/b/boost1.58/libboost-filesystem1.58.0_1.58.0+dfsg-5ubuntu3.1_amd64.deb
sudo dpkg -i libboost-filesystem1.58.0_1.58.0+dfsg-5ubuntu3.1_amd64.deb
````
Thanks @Kwaskoff

**Comment by Shekelme** [comment]
> sudo dpkg -i libboost-filesystem1.58.0_1.58.0+dfsg-5ubuntu3.1_amd64.deb

libboost-filesystem1.58.0:amd64 depends on libboost-system1.58.0, but in my Ubuntu 18.04.4's packages I can find only 62 and 65 versions...
