### ISSUE TITLE
Not finding unspent transactions

### ISSUE THREAD

**Issue by z7z3** [LIMXTEC/BitSend#86]
I was setting up a masternode and I used importprivkey with rescan to add to the wallet the address holding the funds for the masternode. I previously sent the 25000 coins to this address in one transaction and the amount is shown as unspent in the block explorer. It has over 3000 confirmations.

The listtransactions command shows the transaction for this address where the funds for the maternode was received on this address.

The listunspent command however returns an empty set even though the coins have not been spent and my node is caught up on the bitsend blockchain.

If I try masternode start-many I get the error "could not allocate vin" and debug.log contains:
2018-01-06 15:21:23 CActiveMasternode::GetMasterNodeVin - Could not locate valid vin
2018-01-06 15:21:23 CActiveMasternode::Register() - Error: could not allocate vin

Has anyone else encountered this? Am I missing something?

**Comment by limxdev** [comment]
Please unlock your amount. 

Kind Regards Christian

**Comment by z7z3** [comment]
I did not encrypt the wallet, so there is nothing to unlock. But I did use importprivkey to add the funds to the wallet. Could this be causing the problem?

**Comment by wfthkttn** [comment]
@z7z3 There is coin-control features that "Locks" transactions to prevent occasional spending.
They can be found at settings->options->wallet->Enable coin control...
Then Inputs... Button will appear on "send" tab. Rightclick on TX you wish -> unlock
