### ISSUE TITLE
current linux-bitsendd is not static

### ISSUE THREAD

**Issue by bumbacoin** [LIMXTEC/BitSend#92]
running it gives
`bitsendd: error while loading shared libraries: libdb_cxx-4.8.so: cannot open shared object file: No such file or directory`

**Comment by limxdev** [comment]
Try this here
sudo apt-get install libdb4.8-dev
sudo apt-get install libdb4.8++-dev

Kind Regards Christian

**Comment by bumbacoin** [comment]
is it not possible to release a static daemon?

also to install bdb4.8 are necessary.
```
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get upgrade
```
