### ISSUE TITLE
Masternode stops after 2-3 minutes

### ISSUE THREAD

**Issue by Corsten56** [LIMXTEC/BitSend#94]
Hello.

My masternode worked 75 days before and stopped 2 or 3 days ago.
"Bitsendd" stops working after 2-3 minutes.
Nothing changed on VPS.
I've tried all:
1) VPS reboot.
2) Blockchain data removal.
3) Replace blockchain data from https://bitsend.info/forums/index.php?topic=418
4) Yesterday I've reinstalled OS from scratch on my VPS (Vultr + Ubuntu 16.04 + all updates) but problem still the same.
I think I found a bug and problem not on my side or on VPS.

> 2018-07-05 08:21:11 ERROR: AcceptBlockHeader: prev block not found
> 2018-07-05 08:21:11 Misbehaving: 82.46.100.120:49658 peer=7 (0 -> 10)
And server stops after this. What is 82.46.100.120 IP?
Can you check it and give some advices? May be you can provide me debug version or AFAIK new version based on bitcoin core 0.16?
Full debug log from VPS is in attachment. It's so big because scheduler restarts Bitsend daemon.
Password "masternode".
[debug.zip](https://github.com/LIMXTEC/BitSend/files/2165742/debug.zip)

**Comment by dArkjON** [comment]
It looks like your client try to connect to /Urals Core:1.1.0.13/: version 70083, blocks=96050 and after this shutdown. Check your bitsend.conf is there is a line "addnode=82.46.100.120" and remove it. Also try to delete your peers.dat and restart the client.

**Comment by Corsten56** [comment]
It was solved automatically after 3 day idle without any real reason so I still can't understand what it was.
Anyway thank you for your suggestions.

**Comment by dArkjON** [comment]
Today we release the V 0.14.06 with a hotfix for the Server Crash and wrong connected Nodes -> https://github.com/LIMXTEC/BitSend/releases/tag/v0.14.0.6
