### ISSUE TITLE
SOLO Mining

### ISSUE THREAD

**Issue by imrecsoka** [LIMXTEC/BitSend#95]
SOLO Mining, possible, not possible?
I was last told to wait for a wallet update.
Along with this i was told to get a miner that supports or doesnt support getwork/block/template something along those lines.
It would be helpful if the team who believes in this coin would give the proper information regarding this and not let people hand around in limbo

**Comment by dArkjON** [comment]
The original getwork mining protocol simply issues block headers for a miner to solve. The miner is kept in the dark as to what is actually in this block, and has no influence over it. In effect, the authority of the miner to decide which transactions are accepted, etc, is all transferred blindly to the pool operator. A corrupt (or compromised) pool operator could use the combined hash power of all the miners to execute double spend attacks or other similar attacks.

getblocktemplate moves block creation to the miner, while giving pools a way to set down the rules for participation. While pools can do just as much as they could before by expressing it in these rules, miners can not be kept in the dark and are enabled to freely choose what they participate in mining. This improves the security of the Bitcoin network by making blocks decentralized again.

Update your Miner to getblocktemplate there are no plans to go back to the old "getwork" solution.
